### ISSUE TITLE
panel.spacing set for x and y

### ISSUE THREAD

**Issue by Ax3man** [hrbrmstr/hrbrthemes#21]
`theme_ipsum` contains the following two lines (line 155&156):

```
ret <- ret + theme(panel.spacing.x = grid::unit(2, "lines"))
ret <- ret + theme(panel.spacing.y = grid::unit(2, "lines"))
```

Is there a reason `panel.spacing` is not set instead? The x and y inherit from that anyways, and the value set is the same.

The current use can be confusing as `theme_ipsum() + theme(panel.spacing = grid::unit(100, 'lines'))` will actually have no effect.

**Comment by hrbrmstr** [comment]
Thx for taking the pkg for a spin & for taking time to post an issue/q!

The reason is "legacy" and mostly due to how I was using a personal theme
this was based on. I tend to only have to change either x or y spacing and
rarely set both to the same values so it just kinda flowed from that. I've
got no problem rolling it up into just panel.spacing, tho, as it should
have no negative impact on the use of the theme by others.

**Comment by Ax3man** [comment]
Thanks Bob, and thanks for the great theme.
