### ISSUE TITLE
Undefined exports: expand_scale

### ISSUE THREAD

**Issue by pkq** [hrbrmstr/hrbrthemes#26]
Using `devtools::update_packages()` I am getting an undefined exports error for `expand_scale`. Looking at the latest commit, the function is exported in the `NAMESPACE` file and the `expand-scale.r` file exists, but there's no function defined. Thanks!

**Comment by hrbrmstr** [comment]
it may work if load ggplot2 before you install/update it but that might not be possible with `devtools::update_packages()` if you use dev versions of ggplot2.

i'm trying to compensate for an error in the way ggplot2 specifies function links.

I do: https://github.com/hrbrmstr/hrbrthemes/blob/master/R/scales.r#L13 to avoid having to replicate the docs in ggplot2 scales but b/c of https://github.com/tidyverse/ggplot2/blob/4255cd8341ad1072036186e5d34ad2c1b12221b3/R/scale-discrete-.r#L12 it fails miserably. I'm not inclined to replicate the scales docs, but i agree this def needs to be kept open since this won't get to CRAN the way I've got it. 

i was avoiding just making a local "alias" for the ggplot2 function b/c then i have to declare all the stuff i use from ggplot2 but that may make more sense now due to this issue. 

i'll poke at it and really appreciate this report as i wld not have seen it on my end.

**Comment by hrbrmstr** [comment]
I just pushed up what I'm hoping is a quick fix (as I didn't get any errors on my end and the README + test suite works fine). Give it a go when you get a chance pls.

**Comment by pkq** [comment]
Thanks for the quick response. This results in a different error: ` 'expand_scale' is not an exported object from 'namespace:ggplot2'`. This occurs immediately after `** preparing package for lazy loading`, whereas before, devtools would install the help and vignettes, and then error out at `** testing if installed package can be loaded`. Let me know if there's any other information that would be useful.

**Comment by hrbrmstr** [comment]
This is super helpful. Are you running CRAN ggplot2 or GH? I think the issue is it's exported in GH ggplot2 (https://github.com/tidyverse/ggplot2/blob/master/NAMESPACE#L275) but not CRAN ggplot2

**Comment by hrbrmstr** [comment]
ok, i bit the bullet and just reproduced the roxygen docs. can you give it a go(as you have time) and also make sure i got your details right in the DESCRIPTION file? (this has been rly rly helpful and I'd like to add you as a contributor)

**Comment by pkq** [comment]
Yes, running CRAN ggplot2. Reproducing the oxygen docs seems to have worked; installation is successful, and the package loads as expected. Out of curiosity, what made you decide to reproduce, rather than require GH ggplot2? 

Thanks again for responding so quickly, and for offering to list me as a contributor. Yes, details are correct. 👍

**Comment by hrbrmstr** [comment]
Just reproduced the roxygen. No choice, really. The `expand` param changed
behaviur and my non-duplicate-roxygen workaround wld have been fine with
new GH and new eventual CRAN ggplot2 but broke with older b/c that function
doesn't exist outside of new GH ggplot2. But the new GH ggplot2 docs refer
to it so the first hack failed faux export) and i shld have realized that
wld have meant the second hack (stub export) failed. So, the only way for
both CRAN ggplot2 and GH ggplot2 compatibility was to bite the bullet and
reproduce the `@param` docs (it's an easy cut/paste but it also means i
have to maintain it). It would have come back to bite me in a few weeks
(likely going back to CRAN in early Dec) so this was a huge help and saved
me much time (likely hours) later. Rly appreciate you taking the time for
this (and for using the pkg :-)!

**Comment by pkq** [comment]
Glad it was helpful. I really appreciate you making it so easy to make great looking plots!
