### ISSUE TITLE
supporting applying `hrbrthemes` themes to labels in `ggplot2`

### ISSUE THREAD

**Issue by IndrajeetPatil** [hrbrmstr/hrbrthemes#60]
I noticed that, after applying the `hrbrthemes`, although the subtitle, title, caption, legend, axes-titles, etc. all change, the labels inside the plot remain unaffected. And I was wondering if it would be possible to also apply theming to this component of the plot. 

Otherwise, there are two different font-families in the same plot, one for non-labels and one for labels.

Thanks for considering.

``` r
library(ggrepel)
#> Loading required package: ggplot2
library(ggplot2)
library(hrbrthemes)
#> NOTE: Either Arial Narrow or Roboto Condensed fonts are required to use these themes.
#>       Please use hrbrthemes::import_roboto_condensed() to install Roboto Condensed and
#>       if Arial Narrow is not on your system, please see https://bit.ly/arialnarrow

p <- ggplot( mtcars, aes(wt, mpg, label = rownames(mtcars), colour = factor(cyl))) +
  geom_point() + 
  labs(title = "This is my title",
       subtitle = "This is my subtitle",
       caption = "This is my caption")

# without `hrbrthemes`
set.seed(123)
p + geom_label_repel() 
#> Warning: ggrepel: 14 unlabeled data points (too many overlaps). Consider
#> increasing max.overlaps
```

![](https://i.imgur.com/rQqIGfY.png)

``` r
# with `hrbrthemes`
set.seed(123)
p + geom_label_repel() + hrbrthemes::theme_ipsum_tw()
#> Warning: ggrepel: 19 unlabeled data points (too many overlaps). Consider
#> increasing max.overlaps
```

![](https://i.imgur.com/c4kcGNb.png)

<sup>Created on 2021-03-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by hrbrmstr** [comment]
`geom_label()` (and the `repel` versions) take a `family` argument and the `text` `theme()` setting applies to (via the help topic):

```
@param text all text elements (element_text())
```

The geoms wont inherit from it but you can make a session-wide change of the defaults:

```
for (geom in c("label", "text", "label_repel", "text_repel")) {
  update_geom_defaults(geom, list(family = font_tw))
}
```

to have it automatically applied w/o having to specify `family` every time.

{hrbrthemes} does have `hrbrthemes::update_geom_font_defaults()` for this very situation, but it will only apply the specified aesthetics to `label` and `text` since I didn't want to check for or depend on {ggrepel}.
