### ISSUE TITLE
Arial Narrow is not a family

### ISSUE THREAD

**Issue by dmi3kno** [hrbrmstr/hrbrthemes#8]
Not sure if it is only on my Windows 7 PC, but Arial Narrow is not its own family. It is a member of the Arial family and regardless of my attempts I could not make it to show in the list of installed fonts as a separate items. Had to enforce mapping like this. 

```
if (is.null(unlist(windowsFonts("Arial Narrow"))))
      windowsFonts(`Arial Narrow`=windowsFont("TT Arial Narrow"))
if (is.null(unlist(windowsFonts("Roboto Condensed"))))
      windowsFonts(`Roboto Condensed`=windowsFont("TT Roboto Condensed"))
if (is.null(unlist(windowsFonts("Roboto Condensed Light"))))
      windowsFonts(`Roboto Condensed Light`=windowsFont("TT Roboto Condensed Light"))
```
Is there a better way to check and enforce the mapping?

Side question: is there a way to force font family into annotations, text and labels (including repel) in one go?

References:
https://journal.r-project.org/archive/2015-1/qiu.pdf
http://blog.revolutionanalytics.com/2012/09/how-to-use-your-favorite-fonts-in-r-charts.html

**Comment by hrbrmstr** [comment]
I'm totally familiar with how fonts work in R, but thx for the refs. It worked on win-builder and CRAN (the test includes using the font) so I'm not sure what's happening on your Windows 7 system but it is something I can test since it's one of the only Windows VMs I get.

I'll add more text updating for other geoms (but you can follow that example in the source for others) and see what might be causing the `_repel` version to not catch it.

thx.

**Comment by hrbrmstr** [comment]
i've done what I can with this and there's now info abt Arial Narrow when the package loads if it's missing.
